server:
  port: 10002

spring:
  application:
    name: security-session-service
  redis:
    host: localhost
    port: 6379

  cloud:
    #consul作为注册中心
    consul:
      host: localhost #配置consul地址
      port: 8500 #配置consul端口
