server:
  port: 6001


spring:
  application:
    name: apiopen-service

  redis:
    host: localhost
    port: 6379


#apiopen的api地址
apiopen:
  url:
    base: https://api.apiopen.top
    wangYiNews: ${apiopen.url.base}/getWangYiNews
