server:
  port: 10009
spring:
  application:
    name: data-jpa-dto
  datasource:
    url: jdbc:mysql://localhost:33306/dto
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true