server:
  port: 6003

spring:
  application:
    name: isoyu-service
  cloud:
    consul:
      host: localhost
      port: 8500


isoyu:
  url:
    base: https://api.isoyu.com/api
    picture:
     cosplay: ${isoyu.url.base}/picture/index?page={page}
     huaban: ${isoyu.url.base}/picture/hua_ban
    news:
      banner: ${isoyu.url.base}/api/News/banner

